CommunityBot/CommandHandler.cs
added when a user joined a dm will be send with the server name and display how to use the ``help`` command (for when it will get added)
=> Added simple dm welcome message in CommandHandler.cs

CommunityBot/CommandHandler.cs, CommunityBot/CommunityBot.csproj, CommunityBot/Program.cs, CommunityBot/Timers.cs
Added an simple (editable) help timer for the #general channel (every 2 hours)
=> Added an help timer for the #general channel (every 2 hours)

CommunityBot/Modules/Misc.cs
Added add, subtract, multiply and divide commands.
All of these commands use 2 integers (which are all the same)
My Username Is HAWQ Nite#0001 <3
=> Added Commands (add, subtract, multiply, divide)

CommunityBot/CommunityBot.csproj, CommunityBot/Features/Economy/Slots.cs, CommunityBot/Global.cs, CommunityBot/Modules/Economy.cs
**AND WAIT! THERE IS EVEN MORE ECONOMY!**
Added commands are:
slots <amount to bet> --- aliased with "slot" try your luck and win or lose some Miunies
newslots <optional parameter: amount of pieces per cylinder> --- aliased with "newslot" creates a new slotmachine to use
showslots --- aliased with "showslot" shows how the three cylinders of the current slot machine are set up
It is not balanced yet - ratios have to be finetuned
NOTE:
I am not particular happy with this code... but wanted to show it anyways since I have it but I don't mind if you don't want to merge / look at this mess :D
=> Added minigame for the economy: Slots

CommunityBot/Features/Economy/Slots.cs, CommunityBot/Modules/Economy.cs
- Removed the multiple edits of the sent message to show the Slots "turning".
- Moved some code from the commands into the actual Slots class where it belongs
=> Some general code improvements of Slots

CommunityBot/Entities/GlobalUserAccount.cs, CommunityBot/Modules/Economy.cs, CommunityBot/Modules/RepeatedTasks.cs
- `ShowRichest` aliased with `Top` and `Top10` shows the richest 10 guild members
- `ShowRichest <pagenumber>` shows a specific page of the list to see lower ranked people
=> Show richest guild members

CommunityBot/CommunityBot.csproj, CommunityBot/Entities/GlobalGuildAccount.cs, CommunityBot/Modules/ServerBots.cs, CommunityBot/Program.cs
The server bots module is allows for you to submit your invite links for bots to a queue so that the server's managers can add them to the server anytime easily.
=> Add ServerBots Module

CommunityBot/Global.cs
Added a function "SendWebRequest" in class "Global" which makes interacting with web apis really easy. (Will be used in later commits of mine)
It takes a GET url and returns awaitable the json respond string. If the response was successfull - otherwise the StatusCode of the request
=> Web Requests

CommunityBot/Global.cs, CommunityBot/Modules/Misc.cs
Added version command, made a global variable containing the version make sure to change it to the current version. That's all thanks!
=> Added version command.

CommunityBot/Configuration/BotSettings.cs, CommunityBot/Global.cs, CommunityBot/Modules/Admin.cs
I made the global version get it from the assembly and made it read only. I also added a response to the set game command and added some rough ideas for purging messages.
=> Added assembly to version command and some other things

CONTRIBUTING.md
Many people don't know but that documentation is actually outdated so I just corrected it.
=> Update on CONTRIBUTING.md

CommunityBot/Features/Economy/Daily.cs, CommunityBot/Modules/Economy.cs
- Now shows the remaining time till the daily refreshes if used during the cooldown time.
- Changed one instance where DateTime.Now instead of DateTime.UtcNow was used which resulted in the actual cooldown being 2 hours longer since the bot runs in the timzone UTC+2
=> Command "Daily" update

CommunityBot/Modules/Misc.cs
=> Fixed Divide command (with the other calculator commands)

CommunityBot/Entities/GlobalGuildAccount.cs, CommunityBot/Entities/GlobalUserAccount.cs, CommunityBot/Entities/IGlobalAccount.cs, CommunityBot/Features/GlobalAccounts/GlobalGuildAccounts.cs, CommunityBot/Features/GlobalAccounts/GlobalUserAccounts.cs
=> Implementation of IEquality of Accounts

.gitignore, CommunityBot/Features/Annoncements.cs, CommunityBot/Handlers/BlogHandler.cs, CommunityBot/Handlers/CommandHandler.cs, CommunityBot/Handlers/DiscordEventHandler.cs, CommunityBot/Modules/ServerBots.cs, CommunityBot/Program.cs
* **Now using Dependency Injection**
DiscordSocketClient, CommandService, CommandHandler and DiscordEventHandler are the services so far. Not all are used everywhere yet... Global.Client is still used in most cases and this should be changed to inject the DiscordSocketClient object instead. But it is a step in the right direction.
* **Add Class / Service: DiscordEventHandler**
While moving to DI I noticed that subscriptions to events are scattered all around and burried in code everywhere so I decided to create a service called DiscordEventHandler and to move all subscriptions to events there and move some event functions to classes where they belong (e.G. UserJoined / UserLeft from Program.cs to Announcements.cs & ReactionAdded from Program.cs to BlockHandler)
* **Cleanup of Program.cs** …
=> Code Reformating

CommunityBot/Modules/Economy.cs
Adding medals to users via switch statement where it is deciding via position of user.
=> Add medal emojis to "top" listing GH fixes #54

CommunityBot/CommunityBot.csproj, CommunityBot/DiscordClientFactory.cs, CommunityBot/InversionOfControl.cs, CommunityBot/Program.cs
Implemented new `InversionOfControl.cs` and `DiscordClientFactory` classes.
The point of the InversionOfControl class is to be able to resolve dependencies in a rich manner, being able to define factories and particular constructors.
:information_source: I just implemented the IoC container, I didn't fully optimize the system to utilize it to its full potential. That can be done with another Pull Request. :+1: 
**What I'm expecting from a code review**
Conformation that I have not broken someone's feature in a subtle way. :slightly_smiling_face:
=> Implement Inversion of Control container with Lamar

CommunityBot/Configuration/BotSettings.cs, CommunityBot/Configuration/DataStorage.cs, CommunityBot/Constants.cs, CommunityBot/Entities/BotConfig.cs, CommunityBot/Entities/GlobalGuildAccount.cs, CommunityBot/Entities/IGlobalAccount.cs, CommunityBot/Features/Blogs/BlogItem.cs, CommunityBot/Features/Economy/Daily.cs, CommunityBot/Features/Economy/Slots.cs, CommunityBot/Features/RoleAssignment/RoleByPhrase.cs, CommunityBot/Features/Trivia/TriviaGame.cs, CommunityBot/Features/Trivia/TriviaGames.cs, CommunityBot/Handlers/EmbedHandler.cs, CommunityBot/Handlers/MessageRewardHandler.cs, CommunityBot/Helpers/ActionResult.cs, CommunityBot/Helpers/GitHub.cs, CommunityBot/Modules/Basics.cs, CommunityBot/Modules/Blogs.cs, CommunityBot/Modules/Economy.cs, CommunityBot/Modules/Fun/Trivia.cs, CommunityBot/Modules/Misc.cs, CommunityBot/Modules/Prefix.cs, CommunityBot/Modules/ServerBots.cs, CommunityBot/Modules/SetTimeZone.cs, CommunityBot/Modules/Tags.cs, CommunityBot/Preconditions/NoSelf.cs, CommunityBot/Preconditions/RequireBotHigherHirachy.cs, CommunityBot/Program.cs, CommunityBot/ServerActivityLogger/ServerActivityLogger.cs
cleaned out commented code and showed in Misc.cs on addembedbuilder can throw an exception if field value is higher then 1024 characters
=> code cleanup and issue help

CommunityBot/Modules/Misc.cs
Added a command for bug reporting
_What issue does this pull request relate to? If none, please create the issue first._ :+1:
_Please describe your changes._
_Please describe what feedback you're looking for. This is a good place to mention your code is perhaps a Work In Progress or a Draft and might change._
=> Bug report command GH#97

CommunityBot/Features/BlackBox.cs, CommunityBot/Program.cs
BlackBox is a class that handles Unhandled exceptions and creates a
BlackBox log file with the date and time of the exception happening
This will help solve issue #121 and solves #106.
* Created a new BlackBox static class
* Used it in Program.cs
_The BlackBox is a static class, because it doesn't figure in the application itself. It is more of a utility class so I feel it justifies the "staticness". However, if there are other ideas, I'm open to hearing them out._
=> Add basic BlackBox

CommunityBot/Modules/Misc.cs
The help command is not checking for the size of the embed. When the size reaches 6000 characters an exception is thrown and no help is sent. https://github.com/discord-bot-tutorial/Community-Discord-BOT/issues/81
When the help message is more than 6000, truncating it to send less than 6000 length message. At first taking the field range of 10, truncating the EmbedBuild to take only first 10 fields and then reducing the range if the message is still long.
Would love to know if the code can be optimized.
=> Help Message more than 6000 characters

README.md
Fix the Coverage badge in README.
This is a super minor change and will be force-merged to fix an organization issue.
=> Fix Coverage badge in README.md

FIRST-CONTRIBUTION.md
This PR closes #120 
I added a beginner-friendly guide on how to contribute your first time to a repository. There are multiple screenshots and gifs explaining how to do it on both GitHub Desktop and in the command line. 
1. I haven't checked if the command line commands are correct as I'm not super experienced with that. A quick overview of those would be good.
2. I'm assuming that they will be working on the main branch here, which should be fine for a first-time contributor, but let me know if you want branches thrown into this tutorial and I'll add it.
3. Under `7. Create a pull request` there are lots of images and text on the same place. I thought about dividing this chapter up into two parts, one with text only, and another one with images only, or a gif. Not sure if this would add …
=> Add more information to FIRST-CONTRIBUTION.md

CommunityBot/InversionOfControl.cs
Fix reactions to trivia game
Resolve #143
Fix typo in singleton configuration
=> Fix reactions to trivia game

CONTRIBUTING.md
Fixes #145 
Fixed discord server links
=> Fix discord server links for #145

Pages/css/landing-page.css, Pages/index.html
=> fixes #148

.appveyor.yml
_What issue does this pull request relate to? If none, please create the issue first._ :+1:
_Please describe your changes._
_Please describe what feedback you're looking for. This is a good place to mention your code is perhaps a Work In Progress or a Draft and might change._
=> Appveyor config fix

CommunityBot/Modules/Reminder.cs
_What issue does this pull request relate to? If none, please create the issue first._ :+1:
_Please describe your changes._
Small typo in reminder.cs
_Please describe what feedback you're looking for. This is a good place to mention your code is perhaps a Work In Progress or a Draft and might change._
=> small typo
